import type { Metadata } from "next";
import "./globals.css";
import { RedirectToHome } from "@/components/quiz/RedirectToHome";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-full w-full flex flex-col select-none overflow-hidden">
        <RedirectToHome />
        {children}
      </body>
    </html>
  );
}
