import { render, screen } from "@testing-library/react";
import { test, expect, vi } from "vitest";
import RootLayout, { metadata } from "@/app/layout";

/* - Mockando o RedirectToHome, já que a lógica dele é testada separadamente em components/quiz - aqui só importa que ele é renderizado - */

vi.mock("@/components/quiz/RedirectToHome", () => ({
  RedirectToHome: () => <div data-testid="redirect-to-home" />,
}));

/* - Testando os metadados exportados - */

test("should export the correct metadata", () => {
  expect(metadata.title).toBe("Create Next App");
  expect(metadata.description).toBe("Generated by create next app");
});

/* - Testando a composição do layout - */

test("should render RedirectToHome and the children passed to it", () => {
  render(
    <RootLayout>
      <p>conteúdo de teste</p>
    </RootLayout>,
  );

  expect(screen.getByTestId("redirect-to-home")).toBeInTheDocument();
  expect(screen.getByText("conteúdo de teste")).toBeInTheDocument();
});
